### ISSUE TITLE
The menu doesnt go away, and obstructs half the screen

### ISSUE THREAD

**Issue by gee842** [BHSPitMonkey/MusicTrainer#15] opened 2016-05-15 10:08 UTC
The menu in the top left corner you open to switch between the modes wont go away, and opens on default without actually tapping the button, even on refresh

Chrome, iOS

**Comment by BHSPitMonkey** [comment] 2016-05-16 05:41
There's an issue with Material UI that can lead to that, generally only if you've opened the menu by swiping from the left edge. Swiping from the left edge again can usually fix it. I'm working on integrating an updated version, and I'll see if the bug has been fixed.

However, refreshing the page (or closing the tab / process) should definitely make the drawer go away; it's not really possible that it wouldn't, and I can't reproduce that issue on my iOS device.

**Comment by BHSPitMonkey** [comment] 2016-05-16 06:16
I think this is now fixed due to the new version of Material UI; I can no longer reproduce the issue.

**Closed as completed by BHSPitMonkey** 2016-05-16 06:16 UTC
Labels: bug
